# Generated by Django 5.0 on 2023-12-21 14:43

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.FileField(
                blank=True, null=True, upload_to=server.models.server_banner_upload_path
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=server.models.server_icon_upload_path
            ),
        ),
    ]
