# Generated by Django 5.0 on 2023-12-21 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_channel_banner_channel_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_server",
                to="server.server",
            ),
        ),
    ]
